<?php

$sLangName = 'English';

$aLang = array(
    'charset'                                       => 'UTF-8',
    'NASCORE_ARTICLE_MAIN_PACKAGINGUNIT'            => 'Packaging unit',
    'DISCOUNT_MAIN_AMOUNT_PACKAGE_UNIT'             => 'Purchase quantity equals packaging unit',
    'NASCORE_ARTICLE_MAIN_UNIQUE'                   => 'Article is unique',
    'NASCORE_ARTICLE_MAIN_NEW'                      => 'Article is new',
    'PROMOTIONS_BANNER_ASSIGNEDCATEGORY'            => 'Assigned category',
    'PROMOTIONS_BANNER_NONE'                        => 'Assigned object',
    'GENERAL_ASSIGNCATEGORY'                        => 'Assign category',
    'PROMOTIONS_BANNER_TEXT'                        => 'Short Description',
    'PROMOTIONS_ARTICLE_ASSIGNCATEGORY'             => "Assign category",
    'PROMOTIONS_ARTICLE_UNASSIGNACATEGORY'          => "Delete category assignment",
    'NASCORE_ARTICLE_MAIN_AMOUNT_IN_PU'             => 'Article can be ordered only in PU.',
    'nastiles'                                      => 'Tiles',
    'tbctile_main'                                  => 'Main',
    'PROMOTIONS_MAIN_TYPE_TILE'                     => 'Tile',
    'PROMOTIONS_TILE_PICTUREANDLINK'                => 'Tile settings',
    'TOOLTIPS_NEWTILE'                              => 'New Tile',
    'PROMOTIONS_TILE_COLOR'                         => 'Select color',
    'PROMOTIONS_SLIDER_COLOR'                       => 'Select text color',
    'NASCORE_ARTICLE_STOCK_PACKAGINGPOINTS'         => 'Packaging-Points',
    'NASCORE_ARTICLE_STOCK_SPOT'                    => 'Storage-Place',
    'points'                                        => 'Points',
    'DELIVERY_MAIN_CHILD'                           => 'Child',
    'DELIVERY_MAIN_FIT_BY_CART'                     => 'Apply multiple times',
    'ARTICLE_MIN_DELIVERY'                          => 'minimum shipping method',
    'DELIVERY_MAIN_SURCHARGE'                       => 'Apply island surcharge',
    'SHOP_OPTIONS_GROUP_SHIPPING'                   => 'Bulky goods',
    'SHOP_CONFIG_DELIVERY_MAX'                      => 'Charge up to',
    'SHOP_CONFIG_CARGO_PRICE'                       => 'Price',
    'ARTICLE_STOCK_BULKY_GOOD'                      => 'Bulky good',
    'ARTICLE_STOCK_BULKY_GOOD_MULTIPLIER'           => 'Number of bulky packages',
    'CONTENT_MAIN_SUB_CATEGORY'                     => 'subcategory',
    'CONTENT_MAIN_SELECT_CATEGORY'                  => 'inserted under:',
    'MX'                                            => 'Mx',
    'COMP'                                          => 'Company',
    'GENIMPORT_AUTOFILL'                            => ' Automatically map CSV fields',

);